"""add encounter card_json cache and audit_logs queue_reset action

Revision ID: ac57618deebf
Revises: f9591df152d5
Create Date: 2026-09-18 11:41:32.839211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac57618deebf'
down_revision: Union[str, Sequence[str], None] = 'f9591df152d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('card_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Not autogenerated: Alembic's autogenerate diff doesn't detect a new
    # member added to a Python enum, and on Postgres, AuditAction backs a
    # native ENUM type (see f9591df152d5) — adding a value there needs
    # ALTER TYPE, not a column change. ADD VALUE has been safe to run inside
    # a transaction since Postgres 12; IF NOT EXISTS makes it idempotent.
    # SQLite has no native enum type at all (the column is plain VARCHAR,
    # validated by SQLAlchemy at the ORM layer), so there is nothing to do
    # there — Base.metadata.create_all(), which is what the test suite uses,
    # always reflects the current AuditAction members regardless.
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'QUEUE_RESET'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'card_json')
    # ### end Alembic commands ###

    # Postgres cannot drop a single value from a native enum type without
    # recreating it (and rewriting any row that used it) — left as a
    # documented one-way migration for QUEUE_RESET specifically.
