"""audit_logs append-only enforcement (BEFORE UPDATE / DELETE triggers)

Revision ID: b0fa02db033d
Revises: ac57618deebf
Create Date: 2026-09-19 04:45:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b0fa02db033d'
down_revision: Union[str, Sequence[str], None] = 'ac57618deebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Not autogenerated: Alembic's diff only looks at columns/tables/constraints,
# never triggers, and op.create_table() (used by the initial migration)
# builds its own plain Table object rather than importing the ORM model —
# so the SQLAlchemy DDL events registered on AuditLog.__table__ in
# backend/models/audit_log.py (which cover Base.metadata.create_all(), i.e.
# the test suite) never fire for a database built by `alembic upgrade head`.
# This migration is what actually puts the same triggers on a real
# (Postgres or SQLite) deployment. Keep both in sync if either changes.

_SQLITE_NO_UPDATE = """
    CREATE TRIGGER audit_logs_no_update
    BEFORE UPDATE ON audit_logs
    BEGIN
        SELECT RAISE(ABORT, 'audit_logs is append-only: UPDATE is not allowed');
    END
"""

_SQLITE_NO_DELETE = """
    CREATE TRIGGER audit_logs_no_delete
    BEFORE DELETE ON audit_logs
    BEGIN
        SELECT RAISE(ABORT, 'audit_logs is append-only: DELETE is not allowed');
    END
"""

_POSTGRES_FUNCTION = """
    CREATE OR REPLACE FUNCTION audit_logs_append_only() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'audit_logs is append-only: % is not allowed', TG_OP;
    END;
    $$ LANGUAGE plpgsql
"""

_POSTGRES_NO_UPDATE = """
    CREATE TRIGGER audit_logs_no_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only()
"""

_POSTGRES_NO_DELETE = """
    CREATE TRIGGER audit_logs_no_delete
    BEFORE DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only()
"""


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute(_POSTGRES_FUNCTION)
        op.execute(_POSTGRES_NO_UPDATE)
        op.execute(_POSTGRES_NO_DELETE)
    elif bind.dialect.name == 'sqlite':
        op.execute(_SQLITE_NO_UPDATE)
        op.execute(_SQLITE_NO_DELETE)
    # Any other dialect: no-op rather than fail the migration outright —
    # append-only enforcement degrades to application-layer-only there,
    # same as before this migration existed.


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_update ON audit_logs")
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_delete ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS audit_logs_append_only()")
    elif bind.dialect.name == 'sqlite':
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_update")
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_delete")
